### ISSUE TITLE
Describe the build process

### ISSUE THREAD

**Issue by Zearin** [docbook/xslt20-stylesheets#26]
Hey @docbook ,

Can you describe:

- [ ] how to build these (anything more complex than `ant build.xml`)
- [ ] a high-level overview of what happens during a build

I want to contribute, but I don’t understand what is happening.  Some of the changes I made broke the build, and I want to be able to fix the problem so I can send a Pull Request.  

In other words…**Help me help you.** :)

**Comment by Zearin** [comment]
Well, that’s at least something.  Thanks, @ndw.  :)

**Comment by ndw** [comment]
I'm open to bugs about what needs to be improved @Zearin :-)
