### ISSUE TITLE
Broken resolving from 261fffd21

### ISSUE THREAD

**Issue by BhaaLseN** [docbook/xslt20-stylesheets#30]
I'm not exactly sure if this might be a problem with Saxon-HE running on .NET, but with the change from 261fffd21 I get some interresting behavior.

$resolved ends up with a value of "file://D:/work/docbook/common/locales/en.xml", and with "file:/" stripped off front the path "/D:/work/docbook/common/locales/en.xml" is used.
Saxon then passes this one to a XmlResolver (in .NET) which gets an URI of "file://D:/D:/work/docbook/common/locales/en.xml" which of-course is an invalid path. In the end, a NotSupportedException is thrown and Saxon returns "FODC0002: Document has been marked not available"
Reverting the change lets the stylesheet continue just fine, so I don't really know why this change was made, but it certainly breaks things on my end.

**Comment by ndw** [comment]
Also resolved along with #36 I think.
