### ISSUE TITLE
Broken build and missing files

### ISSUE THREAD

**Issue by kosek** [docbook/xslt20-stylesheets#33]
Hi Norm,

I tried to refresh my local copy and develop transclusion preprocessing step along updating the spec. However it seems that build is broken, after running ant I'm getting errors below. Is the actual code supposed to work or is repo in a middle of some refactoring?

Thx,

Jirka

use-xproc:
     [java] Failed to create log: file:/tmp/out.xml
     [java] XI 28, 2014 4:36:32 ODP. com.xmlcalabash.util.DefaultXProcMessageLis
tener error
     [java] SEVERE: file:/e:/src/dbxslt2/tests/xspec/functions.xml:err:XTSE0165:
I/O error reported by XML parser processing file:/e:/src/dbxslt2/xslt/base/html/
docbook.xsl: e:\src\dbxslt2\xslt\base\html\docbook.xsl (The system cannot find t
he file specified)
     [java] XI 28, 2014 4:36:32 ODP. com.xmlcalabash.util.DefaultXProcMessageLis
tener error
     [java] SEVERE: Failed to compile stylesheet. 1 error detected.
     [java] XI 28, 2014 4:36:32 ODP. com.xmlcalabash.util.DefaultXProcMessageLis
tener error
     [java] SEVERE: Failed to compile stylesheet. 1 error detected.
     [java] XI 28, 2014 4:36:32 ODP. com.xmlcalabash.drivers.Main error
     [java] SEVERE: Pipeline failed: net.sf.saxon.s9api.SaxonApiException: Faile
d to compile stylesheet. 1 error detected.
     [java] XI 28, 2014 4:36:32 ODP. com.xmlcalabash.drivers.Main error
     [java] SEVERE: Underlying exception: javax.xml.transform.TransformerConfigu
rationException: Failed to compile stylesheet. 1 error detected.
     [java] Java Result: 1

**Comment by ndw** [comment]
The whole thing is gradle now. That should be better. Please let me know if you have more troubles.
