### ISSUE TITLE
Smoketests fail on image scaling. What does this mean for other processing?

### ISSUE THREAD

**Issue by rwdalpe** [docbook/xslt20-stylesheets#34]
When building version 2.0.7 the smoketests fail with the following message

> Cannot read image properties for http://docbook.github.com/latest/img/1.png. (No extension)

Looking through the templates that message is coming from graphics.xsl and appears to be due to the fact that the `magick:wand` function is not available. I'm not sure whether that's supposed to be some sort of imagemagick extension or something specific to MarkLogic (as the namespace seems to suggest).

Is there any way to make this function available, or if not what will it mean for image processing? The smoketest output scales the image to a width of 1755 for a reason unknown to me.

Thank you!

**Comment by rwdalpe** [comment]
My mistake. I didn't realize that the [xslt20-java](https://github.com/docbook/xslt20-java) project existed and contained the files necessary to enable the extensions. For my main project I have started pulling in the latest release and the `No extension` message has disappeared. However it's still around for the xslt20-stylesheets project despite the fact that the extensions JAR is in the classpath and checked into this repository. I assume that there must be a versioning mismatch or something similar.

**Comment by ndw** [comment]
This has been fixed as part of a large-scale infrastructure hack; I've moved to gradle for builds and pulling things from Maven.
