### ISSUE TITLE
Can't access l10n files due to lack of file:

### ISSUE THREAD

**Issue by stevecuzner** [docbook/xslt20-stylesheets#36]
When running with Saxon 9EE from within Oxygen 17, I get the following error:

FODC0002: Document has been marked not available: T:/.../docbook/xslt/base/common/locales/en.xml

reported at line 943, col 0 of base/common/l10n.xsl.

Where ... is redacted file path information. If I execute within Oxygen xpath query builder doc-available('T:/.../docbook/xslt/base/common/locales/en.xml') it returns false. If I add file:/ to the URI doc-available returns true.

I believe this is due to the file:/ and other patterns being removed in the resolve-path function.

I'm running using the stylesheet distribution 2.0.8

**Comment by ndw** [comment]
Some Windows related oddness. Ok. I'll see what I can do.

**Comment by stevecuzner** [comment]
I removed the code that strips file:/ in my local copy and it works fine (yes, I'm running on Windows 7). This from Adrian at Oxygen:

That explains the problem then. doc() takes a URI as argument and removing the file:/ protocol breaks the URI (it becomes a file path of sorts). Some XSLT engines might accept an absolute file path as argument but Saxon only works with URI (or a relative URI).

**Comment by ndw** [comment]
Ah. I see what's going on. Ok. I've separated out the resolution from the stripping of the file:// prefix. I'll post a new release tomorrow (or real soon,anyway).

**Comment by stevecuzner** [comment]
Nice, thanks for the quick turnaround. I’m working on target.db generation now which doesn’t seem to be implemented even though reading a target.db file is. I don’t have permission (yet) from legal to contribute to open source projects, but I’m working on it. If I do get permission, do you have any guidelines for working on the project?

Steve

**Comment by ndw** [comment]
I believe this is fixed in 2.0.9a1 (mislabled 8b) and beyond. Please let me know if you continue to have trouble.
